[project]
name = "bloqade"
version = "0.2.7"
description = "neutral atom software development kit"
authors = [
    {name = "Roger-luo", email = "info@quera.com"},
]
dependencies = [
    "juliacall>=0.9.12",
    "numpy>=1.24.2",
    "matplotlib>=3.7.1",
    "pydantic>=1.10.7",
    "quera-ahs-utils>=0.4.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "twine>=4.0.2",
    "ipython>=8.12.0",
    "black>=23.3.0",
    "pytest>=7.3.1",
    "mypy>=1.2.0",
]

[tool.pdm.scripts]
_.env_file = "./.env"
upload = "python -m twine upload -r bloqade dist/*"
build = {cmd = "pdm build"}
publish = {composite = ["build", "upload"]}
