[project]
name = "bloqade"
version = "0.2.7"
description = "neutral atom software development kit"
authors = [
    {name = "Roger-luo", email = "info@quera.com"},
]
dependencies = [
    "juliacall>=0.9.12",
    "numpy>=1.24.2",
    "matplotlib>=3.7.1",
    "pydantic>=1.10.7",
    "quera-ahs-utils>=0.4.0",
    "pandas>=2.0.1",
    "seaborn>=0.12.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.black]
line-length = 88

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
# Assume Python 3.10.
target-version = "py310"

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "twine>=4.0.2",
    "ipython>=8.12.0",
    "black>=23.3.0",
    "pytest>=7.3.1",
    "mypy>=1.2.0",
    "ipykernel>=6.22.0",
    "jupyter>=1.0.0",
    "ruff>=0.0.264",
    "pre-commit>=3.3.1",
    "coverage>=7.2.5",
]

[tool.pdm.scripts]
_.env_file = "./.env"
upload = "python -m twine upload -r bloqade dist/*"
build = {cmd = "pdm build"}
publish = {composite = ["build", "upload"]}
test = "pytest"
coverage = {shell = "coverage run -m pytest && coverage report"}
