[tool.poetry]
name = "bloqade"
version = "0.1.0"
description = ""
authors = ["QuEra Computing <rluo@quera.com>"]
readme = "README.md"
packages = [{include = "bloqade", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.7"
numpy = "^1.24.2"
juliacall = "^0.9.12"

[tool.poetry.group.dev.dependencies]
ipython = "^8.12.0"
matplotlib = "^3.7.1"
black = "^23.3.0"
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
